# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNBnA6fYls6Ky0wdvB_kGVxlwFjxolPw

# **Practice Questions:**

---

1. Write a Pandas program to create a dataframe from a dictionary and display it.
Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
"""

# Question :01
import pandas as pd
Data = {
    'X':[78,85,96,80,86],
     'Y':[84,94,89,83,86],
     'Z':[86,97,96,72,83]
}

data_set = pd.DataFrame(Data)
data_set

"""2. Write a Pandas program to get the first 3 rows of a given DataFrame.
Sample Python dictionary data and list labels:

    exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}


"""

# Question :02
import numpy as np

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
             }

data_set2 = pd.DataFrame(exam_data)
print(data_set2.iloc[0:3 , :])

"""3. Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.
Sample Python dictionary data and list labels:

"""

# Question:03
data_set2[['name','score']]

"""4. Write a  Pandas program to select the rows where the number of attempts in the examination is greater than 2.

"""

# Question :04
data_set2.loc[(data_set2['attempts'] > 2),['name', 'score' , 'qualify' , 'attempts']]

"""5. Write a Pandas program to count the number of rows and columns of a DataFrame.
Sample  Python dictionary data and list labels:

"""

# Question :05
data_set2.shape